# use google api to search for a term and return the top 10 results

import re
import requests
import json
import sys
requests.packages.urllib3.disable_warnings()
re = re.compile(r'href="(http.*?)"')
print("Enter a search term: ")
search = input()
print ("Enter a number of results: ")
num = input()
print("Enter a file name: ")
file = input()
print("Enter a file type: ")
filetype = input()
print("Enter a site: ")
site = input()
print("Enter a date range: ")
daterange = input()
print("Enter a language: ")
language = input()
print("Enter a country: ")
country = input()
print("Enter a region: ")
region = input()
print("Enter a city: ")
city = input()
print("Enter a state: ")
state = input()
print("Enter a zip code: ")
zipcode = input()
print("Enter a phone number: ")
phone = input()
print("Enter a domain: ")
domain = input()
print("Enter a link: ")
link = input()
print("Enter a title: ")
title = input()
print("Enter a body: ") 

body = input()
print("Enter a cache: ")
cache = input()
print("Enter a related: ")
related = input()
print("Enter a location: ")
location = input()
print("Enter a author: ")
author = input()
print("Enter a publisher: ")
publisher = input()
print("Enter a filetype: ")
filetype = input()
print("Enter a site: ")
site = input()
print("Enter a date range: ")
daterange = input()
## generate the file 
f = open(file, "w")
f.write("Search Term: " + search + " Number of Results: " + num + " File Name: " + file + " File Type: " + filetype + " Site: " + site + " Date Range: " + daterange + " Language: " + language + " Country: " + country + " Region: " + region + " City: " + city + " State: " + state + " Zip Code: " + zipcode + " Phone Number: " + phone + " Domain: " + domain + " Link: " + link + " Title: " + title + " Body: " + body + " Cache: " + cache + " Related: " + related + " Location: " + location + " Author: " + author + " Publisher: " + publisher + " File Type: " + filetype + " Site: " + site + " Date Range: " + daterange)
f.close()
## if all of the errors are not qeuried close the terminal
if (search == "q" or num == "q" or file == "q" or filetype == "q" or site == "q" or daterange == "q" or language == "q" or country == "q" or region == "q" or city == "q" or state == "q" or zipcode == "q" or phone == "q" or domain == "q" or link == "q" or title == "q" or body == "q" or cache == "q" or related == "q" or location == "q" or author == "q" or publisher == "q" or filetype == "q" or site == "q" or daterange == "q"):
    sys.exit()
